### PR TITLE
hypnos i love you so much i made emote for you please accept it

### PR DESCRIPTION
**Pull request by JesterRomut**
🙏🙏🙏🙏🙏🙏

### CODE REVIEW

**Comment by JesterRomut** [comment]
image
have to say this is not gijinka, sorry

**Comment by JesterRomut** [comment]
i tried my best made hypnos multiplayer-able with 1 player (myself), but i have no friend available to test it, but atleast it's better than before ; ;

https://github.com/GinYuH/HypnosMod/assets/77535733/58688fef-a3c5-418b-9b1f-3993e83917d6

**Comment by JesterRomut** [comment]
ok, tested with 3 players (thank you kerubii and randvary)

https://github.com/GinYuH/HypnosMod/assets/77535733/f66630db-feee-48a4-9e3f-442bbb1e9dd9

**Comment by WarmurCle** [comment]
;D

**Comment by GinYuH** [comment]
rad

**Pull request merged**
